// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yunyunbaby/工作文件夹/yunstyle-ui/node_modules/dumi/theme-default/slots/Header/index.js';
